In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

### Часть 1

Источник данных тут https://www.ssa.gov/oact/babynames/limits.html

План:
1. Скачать архив
2. Распаковать
3. Взять данные за 1880 год и присвоить имена колонкам: имя, пол, количество родившихся.
4. Найти сколько всего уникальных имен мальчиков и девочек.
5. Сколько всего родилось мальчиков и девочек.

In [9]:
# ответ 1.3, ваш код
df1880 = pd.read_csv('names/yob1880.txt', names=['Name', 'Gender', 'Births'])
df1880

           Name Gender  Births
0          Mary      F    7065
1          Anna      F    2604
2          Emma      F    2003
3     Elizabeth      F    1939
4        Minnie      F    1746
...         ...    ...     ...
1995     Woodie      M       5
1996     Worthy      M       5
1997     Wright      M       5
1998       York      M       5
1999  Zachariah      M       5

[2000 rows x 3 columns]

In [13]:
# ответ 1.4, ваш код
df1880.groupby('Gender')[['Name']].nunique()

        Name
Gender
F        942
M       1058

In [14]:
df1880.groupby('Gender')[['Name']].count()

        Name
Gender
F        942
M       1058

In [15]:
# ответ 1.5, ваш код
df1880.groupby('Gender')[['Births']].sum()

        Births
Gender
F        90994
M       110490

### Часть 2

План:
1. Собрать единую таблицу из разных файлов
2. Построить сводную таблицу по годам для количества рожденных мальчиков и девочек
3. Рисуем график рождаемости (2 графика matplotlib, seaborn)

In [19]:
# ответ 2.1, ваш код
df_list = []
for y in range(1880, 2025):
    df_temp = pd.read_csv(f'names/yob{y}.txt', names=['Name', 'Gender', 'Births'])
    df_temp['Year'] = y
    df_list.append(df_temp)
df = pd.concat(df_list, ignore_index=True)

df

              Name Gender  Births  Year
0             Mary      F    7065  1880
1             Anna      F    2604  1880
2             Emma      F    2003  1880
3        Elizabeth      F    1939  1880
4           Minnie      F    1746  1880
...            ...    ...     ...   ...
2149472      Zylyn      M       5  2024
2149473    Zymiere      M       5  2024
2149474     Zypher      M       5  2024
2149475       Zyre      M       5  2024
2149476     Zyrell      M       5  2024

[2149477 rows x 4 columns]

In [8]:
# ответ 2.2, ваш код
df.pivot_table(index = 'Year',

In [9]:
# ответ 2.3, ваш код

### Часть 3.

План (пишем свои функции):
1. Найдем для каждого имени долю детей с данным именем относительно общего количества родившихся детей в году в зависимости от пола. Результат добавить отдельным столбцом в таблицу - процент.
2. Отберем 1000 имен самых популярных имен для каждой каждого года в зависимости от пола. Результат сохранить в виде таблицы top_1000

In [10]:
# ответ 3.1, ваш код

In [11]:
# ответ 3.2, ваш код

### Часть 4.

План (построить график):

Найдем по два самых популярных в истории имени мальчиков и девочек и построим графики:

1.	В абсолютном значении - как менялось количество родившихся мальчиков с двумя самыми популярными именами в зависимости от года
2.	В относительном значении - как менялось количество родившихся девочек с двумя самыми популярными именами в зависимости от года
3. Построим в абсолютном значении график для всех четырех имен.

In [12]:
# ответ 4.1, ваш код

In [13]:
# ответ 4.2, ваш код

In [14]:
# ответ 4.3, ваш код

### Часть 5.

Свободное задание: построить зависимость, отражающую растущее разнообразие имен в зависимости от года.

In [15]:
# ответ 5, ваш код

### Часть 6.

Свободное задание: построить тренд, отражающий количество самых популярных имен для 50% родившехся мальчиков и девочек

In [16]:
# ответ 6, ваш код

### Часть 7.

В 2007 году исследователь детских имен Лора Ваттенберг указала на своем веб-сайте, 
что распределение имен мальчиков по последним буквам значительно изменилось за последние 100 лет.

Подтвердите или опровергните это утверждение (в сравнении 1910, 1940, 1970, 2020 года)

А что с девочками?

In [17]:
# ответ 7, ваш код

### Часть 8.

Смена половой предпочтительности имени Leslie-Lesly (корень Lesl). Построить график.

In [18]:
# ответ 7, ваш код